#!/usr/bin/env node
const fw = require('./build')

// Watch
if (process.argv.includes('-w')) {
	fw.watch(() => {
		timed(fw.build)
	})
} else {
	timed(fw.build)
}

function timed(fn) {
	const start = process.hrtime()
	fn()
	const end = process.hrtime(start)

	// If time is under a second, format like "340ms"
	let fmt = `${(end[1] / 1e6).toPrecision(3)}ms`
	if (end[0] > 0) {
		// Otherwise, format like "3.150s"
		fmt = `${end[0]}${(end[1] / 1e9).toPrecision(3).toString().slice(1)}s`
	}
	console.log(`Build finished in ${fmt}`)
}