#!/usr/bin/env node
const fw = require('./build')

// Watch
if (process.argv.includes('-w')) {
	fw.watch(() => {
		timed(fw.build)
	})
} else {
	timed(fw.build)
}

function timed(fn) {
	const start = process.hrtime()
	fn()
	const end = process.hrtime(start)
	console.log(`Build finished in ${end[1] / 1000000}ms`)
}