#!/usr/bin/env node
const til = require('./dist/build')
const browserSync = require('browser-sync').create()

const PROD = process.env.PROD == undefined ? true : process.env.PROD == 'true'

const build = prod => {
	const start = process.hrtime()
	til.build({ prod })
	const end = process.hrtime(start)

	// If time is under a second, format like "340ms"
	let fmt = `${(end[1] / 1e6).toPrecision(3)}ms`
	if (end[0] > 0) {
		// Otherwise, format like "3.150s"
		fmt = `${end[0]}${(end[1] / 1e9).toPrecision(3).toString().slice(1)}s`
	}
	console.log(`Build finished in ${fmt}`)
}

// Watch
if (process.argv.includes('dev')) {
	browserSync.init({
		server: './dist',
		ui: false,
		notify: false,
		open: false,
		logPrefix: '',
	})
	
	// Initial build
	build(false)
	browserSync.reload(['*.html'])

	til.watch(file => {
		// Development build
		build(false)
		const reload = file.endsWith('.css') ? ['*.css'] : ['*.html', '*.css']
		browserSync.reload(...reload)
	})
} else {
	build(PROD)
}